### ISSUE TITLE
Anyway to use locally deployed zenhub?

### ISSUE THREAD

**Issue by ScottChapman** [ilbonzo/node-zenhub#16]
We have github enterprise & zenhub deployed at our company. How can I set the URL to use our deployment?

**Comment by ilbonzo** [comment]
Hi, 
if hi understand the problem, the zenhub url is "hard coded" in 
https://github.com/ilbonzo/node-zenhub/blob/master/lib/_http.js

we could add this value optional in ZenHub contructor like this

```
var ZenHub = function(token, api_base_url) {
    this.credentials = {
        'access_token': token,
        'zenhub_api_base_url': api_base_url
    };
    this._http = new Http(this.credentials);
};
```

**Comment by ilbonzo** [comment]
@ScottChapman @cavoto has solved the issue
