### ISSUE TITLE
Question about getReleaseReportsForRepository

### ISSUE THREAD

**Issue by CSIYI** [ilbonzo/node-zenhub#20]
When I try to make api call `getReleaseReportsForRepository`, I always get not found message, and I feel like maybe something wrong with the url, it used to have 
<pre>
this._http._get('repositories/' + repoId + '/reports/release', {}, function(error, body) {
        callback(error, body);
    });
</pre>
and I change it to to 
<pre>
this._http._get('repositories/' + repoId + '/reports/release<b>s</b>', {}, function(error, body) {
        callback(error, body);
    });
</pre>
then it works. Let me know if I understand it wrong. Thanks.

**Comment by ilbonzo** [comment]
Hi, 
the documentation:
https://github.com/ZenHubIO/API#get-release-reports-for-a-repository

GET /p1/repositories/:repo_id/reports/releases

nice catch.

I'll fix it
